ALTER TABLE "User" ADD COLUMN "notifyBooking" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifyCancellation" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifyReviews" BOOLEAN NOT NULL DEFAULT true;
